
FROM tensorflow/tensorflow:2.0.0-gpu-py3

COPY install/ubuntu_install_core.sh /install/ubuntu_install_core.sh
RUN bash /install/ubuntu_install_core.sh

COPY install/ubuntu_install_build.sh /install/ubuntu_install_build.sh
RUN bash /install/ubuntu_install_build.sh

RUN pip3 install -y torch==1.3.0 pytest gpustat