
FROM tensorflow/tensorflow:2.0.0-gpu-py3

COPY install/ubuntu_install_core.sh /install/ubuntu_install_core.sh
RUN bash /install/ubuntu_install_core.sh

RUN pip3 install torch==1.3.0 
RUN pip3 install pytest gpustat cpplint pylint